version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
     - '27017:27017'

    volumes:
      - db:/data/db

  app:
    container_name: customer_api
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo

volumes:
    db: